cam0:
  T_cam_imu:
  - [0.9994776295729385, -0.00029754917678183335, -0.03231686011585321, 0.1056077687953397]
  - [-0.032314938367398544, 0.005070084708708289, -0.9994648763210031, 0.06206694797376334]
  - [0.00046123916947852367, 0.9999871027695978, 0.005057820963084825, -0.10854025462817145]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.22701592574338186, 0.16509330323230773, -0.00045125021955583287, -0.0011047712932871526]
  distortion_model: radtan
  intrinsics: [1466.5268169839428, 1467.630932257398, 614.1934103491811, 502.4304583835144]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam0/image_raw/debayered
  timeshift_cam_imu: -0.04788495612411291
cam1:
  T_cam_imu:
  - [0.9996018144986042, 0.0021114823244897246, -0.028138125266118204, -0.11694507874146355]
  - [-0.02815252784554572, 0.0071332221753850344, -0.9995781871956304, 0.062363369151573166]
  - [-0.0019098761750870174, 0.9999723290090532, 0.007189825394672167, -0.10788773012788538]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9999883596601945, -0.004168297744210326, 0.0024301930031113772, -0.22202913093990584]
  - [0.0041632841685210606, 0.999989202481545, 0.0020644576185724303, 8.149295051656662e-05]
  - [-0.002438772037092086, -0.002054316003527928, 0.9999949160754328, 0.0010370310877692572]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.22749178030800513, 0.17878313849356778, -0.00020067127981154064, -0.0012739319796487045]
  distortion_model: radtan
  intrinsics: [1468.7962773235292, 1470.6995944145817, 621.3293861301502, 506.12930845473704]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam1/image_raw/debayered
  timeshift_cam_imu: -0.04591368840417789
