cam0:
  T_cam_imu:
  - [0.9999024800904011, 0.0058972943158235105, 0.01265907693384543, -0.12763814703591797]
  - [0.012742713382495646, -0.01436731886802406, -0.9998155846975957, 0.06864213111605896]
  - [-0.0057143297696254855, 0.9998793937612157, -0.01444106529958572, -0.11623294297485133]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.22359952208528652, 0.18013301279972246, 8.971833161885709e-05, -0.0006418898948288513]
  distortion_model: radtan
  intrinsics: [1468.0446900113332, 1470.5184861331863, 628.4430160058982, 524.6186837734336]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam0/image_raw/debayered
  timeshift_cam_imu: -0.049352007944218935
cam1:
  T_cam_imu:
  - [0.9998869045167835, -0.003386720192381223, 0.014652928109543658, 0.09594522571582062]
  - [0.014622575978888464, -0.008819534780457605, -0.9998541874083432, 0.06828059392326948]
  - [0.003515458375030418, 0.9999553719704671, -0.008769014757577409, -0.11633581281460514]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9999549156947516, -0.0018602955572863495, -0.009311599129195998, 0.22262299835552557]
  - [0.001911907513242174, 0.999982843359084, 0.005536930299663376, 0.0005272465116765803]
  - [0.009301139046595911, -0.0055544835873430135, 0.9999413165403832, 0.0014587609529462444]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.2248159914455254, 0.1869834662522296, -0.001118155391212432, -0.00013364553496549318]
  distortion_model: radtan
  intrinsics: [1464.7773978651196, 1466.7706854086039, 622.3774889614617, 497.8389324373634]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam1/image_raw/debayered
  timeshift_cam_imu: -0.04843453781083785
