cam0:
  T_cam_imu:
  - [0.9999595708486451, 0.005756616547750966, -0.006907824122957278, 0.10459164930969904]
  - [-0.007239877582712772, 0.059811013900890886, -0.9981834634919239, 0.06059731569138359]
  - [-0.005332995478985879, 0.9981931195826125, 0.05985027299145368, -0.10826783236241083]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.23058118669358704, 0.2069868374555453, 0.00048474293310671297, -0.0019628720517852073]
  distortion_model: radtan
  intrinsics: [1467.8230543075292, 1468.4710876632716, 616.8332652010711, 500.7242902501667]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam0/image_raw/debayered
  timeshift_cam_imu: -0.04802626929337898
cam1:
  T_cam_imu:
  - [0.9998448691579638, 0.017026816928227863, -0.004508339360260753, -0.1194229805078204]
  - [-0.005615957797468423, 0.06557431329958285, -0.9978318848650335, 0.05964609596053607]
  - [-0.016694269571074886, 0.9977024090081076, 0.06565976258643891, -0.10679619588044585]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9999336059498897, -0.0017202134732029221, 0.011394057997793442, -0.22266983527418913]
  - [0.0016546025929137648, 0.9999820118285204, 0.005765267525793511, -0.0004989942920795651]
  - [-0.011403770530398821, -0.005746032108425547, 0.9999184652423909, 0.003003742180267314]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.21580572877936602, 0.17697690525982543, 0.00019742336189470437, -0.0012039603383526135]
  distortion_model: radtan
  intrinsics: [1464.725578782091, 1466.3459075439137, 616.3969718883648, 509.98933883952196]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam1/image_raw/debayered
  timeshift_cam_imu: -0.04781406298771371
