cam0:
  T_cam_imu:
  - [0.9997645192951209, 0.017861354715586697, -0.012323877892964033, -0.11784671164256705]
  - [-0.011493576332760456, -0.04586570998199646, -0.9988814916449954, 0.06056787423104641]
  - [-0.018406620050397834, 0.9987879197585302, -0.04564961864844996, -0.09473221264852623]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.2202949093470388, 0.1676725472399067, 4.551505688895863e-05, -0.0014125065455005822]
  distortion_model: radtan
  intrinsics: [1474.8047830331018, 1475.2579122866225, 612.0972951493824, 503.41637720534055]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam0/image_raw/debayered
  timeshift_cam_imu: -0.04650743349249267
cam1:
  T_cam_imu:
  - [0.9992746320846644, 0.012428253169141373, -0.03599650254153528, 0.1061412564907465]
  - [-0.03545357433032135, -0.04144341124145745, -0.9985116362526159, 0.0573902271232531]
  - [-0.013901573265764125, 0.9990635526270766, -0.040972723523112764, -0.09644659533032264]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9997049241301762, 0.023900970235996712, -0.004336852736045369, 0.22209472379749967]
  - [-0.02387992568657416, 0.9997031124883963, 0.004841077381546084, -0.005515230006804853]
  - [0.004451271625034869, -0.004736085175376466, 0.999978877615987, -0.0009049613170822977]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.23719076995028227, 0.22508621527877057, -0.0009779783014709801, -0.0017257617530162543]
  distortion_model: radtan
  intrinsics: [1480.7625039815325, 1480.7725696689517, 601.1488604277766, 507.25624444259734]
  resolution: [1224, 1024]
  rostopic: /cam_sync/cam1/image_raw/debayered
  timeshift_cam_imu: -0.04706824866284145
