rectify_stereo_imgs:
  ros__parameters:
    cam0:
      cam_overlaps: [1]
      camera_model: "pinhole"
      distortion_coeffs: [-0.23058118669358704, 0.2069868374555453, 0.00048474293310671297, -0.0019628720517852073]
      distortion_model: "radtan"
      intrinsics: [1467.8230543075292, 1468.4710876632716, 616.8332652010711, 500.7242902501667]
      resolution: [1224, 1024]
      rostopic: "/cam_sync/cam0/image_raw/compressed"
      topic_type: "CompressedImage"
    cam1:
      T_cn_cnm1: [0.9999336059498897, -0.0017202134732029221, 0.011394057997793442, -0.22266983527418913,
                  0.0016546025929137648, 0.9999820118285204, 0.005765267525793511, -0.0004989942920795651,
                  -0.011403770530398821, -0.005746032108425547, 0.9999184652423909, 0.003003742180267314,
                  0.0, 0.0, 0.0, 1.0]
      cam_overlaps: [0]
      camera_model: "pinhole"
      distortion_coeffs: [-0.21580572877936602, 0.17697690525982543, 0.00019742336189470437, -0.0012039603383526135]
      distortion_model: "radtan"
      intrinsics: [1464.725578782091, 1466.3459075439137, 616.3969718883648, 509.98933883952196]
      resolution: [1224, 1024]
      rostopic: "/cam_sync/cam1/image_raw/compressed"
      topic_type: "CompressedImage"
